// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhB3HTsPkfO9Hwpt0O7jh8Cc8a8xTJutc',
    appId: '1:657317497818:web:e62a9eb95b77e04076cee3',
    messagingSenderId: '657317497818',
    projectId: 'socialmediaapp-8cb70',
    authDomain: 'socialmediaapp-8cb70.firebaseapp.com',
    storageBucket: 'socialmediaapp-8cb70.firebasestorage.app',
    measurementId: 'G-LQFQ1BVDT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9fIYJ0hnpYmutaJamBlGbher-uvR6mr8',
    appId: '1:657317497818:android:bc849f1de365cd1c76cee3',
    messagingSenderId: '657317497818',
    projectId: 'socialmediaapp-8cb70',
    storageBucket: 'socialmediaapp-8cb70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi5_Ug7F3rsF2_zmwJtXHdT7AFDWg2jNE',
    appId: '1:657317497818:ios:0b9c11fab120730376cee3',
    messagingSenderId: '657317497818',
    projectId: 'socialmediaapp-8cb70',
    storageBucket: 'socialmediaapp-8cb70.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaapp',
  );
}
